apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: supevqig2-python
  janus-idp.io/tekton: supevqig2-python
  backstage.io/kubernetes-id: supevqig2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: supevqig2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
